// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Mn8ZWyxzQL72Drzd1-MyilcLHcHRCEM',
    appId: '1:104615336646:web:240788b12c18b77ca115c7',
    messagingSenderId: '104615336646',
    projectId: 'demorentapp-24ba1',
    authDomain: 'demorentapp-24ba1.firebaseapp.com',
    storageBucket: 'demorentapp-24ba1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiiVaO7xtIBT4C_3HiL4aHunkxGJlHDac',
    appId: '1:104615336646:android:1370288ceb41df13a115c7',
    messagingSenderId: '104615336646',
    projectId: 'demorentapp-24ba1',
    storageBucket: 'demorentapp-24ba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0vCuKH33l2rjWqAOoz99q-XZ0gg5ezMk',
    appId: '1:104615336646:ios:784abf84b7aa1818a115c7',
    messagingSenderId: '104615336646',
    projectId: 'demorentapp-24ba1',
    storageBucket: 'demorentapp-24ba1.firebasestorage.app',
    iosBundleId: 'com.example.demoRentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0vCuKH33l2rjWqAOoz99q-XZ0gg5ezMk',
    appId: '1:104615336646:ios:784abf84b7aa1818a115c7',
    messagingSenderId: '104615336646',
    projectId: 'demorentapp-24ba1',
    storageBucket: 'demorentapp-24ba1.firebasestorage.app',
    iosBundleId: 'com.example.demoRentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Mn8ZWyxzQL72Drzd1-MyilcLHcHRCEM',
    appId: '1:104615336646:web:0b2abe12db6c912ea115c7',
    messagingSenderId: '104615336646',
    projectId: 'demorentapp-24ba1',
    authDomain: 'demorentapp-24ba1.firebaseapp.com',
    storageBucket: 'demorentapp-24ba1.firebasestorage.app',
  );
}
